<?php
/*
Template name: Nuestra historia
*/
get_header(); ?>

<div class="container body">
<div class="col-md-12 bloque">
		<section class="seccion-area">
		<span class="subtitulo"> Institucional </span>
		<h1 class="titulo-pag">NUESTRA HISTORIA</h1>
		<p class="copete">No fue una casualidad que en 1985 surgiera la necesidad de darle realidad a una vieja aspiración de los docentes universitarios como era tener un gremio nacional. </p>

		<hr>
		<p class="cuerpo">La aparición de la histórica CONADU era el producto de una gran transformación cuantitativa y cualitativa del lugar de los docentes universitarios en el nuevo panorama laboral y político de los primeros años posdictadura. Lo explicaba el crecimiento numérico de los cuadros docentes, la creación de varias universidades y carreras y en el caso de la UBA la presencia del CBC, todo esto en el marco del incipiente plan Austral que comenzaba una agresión presupuestaria que no se detuvo hasta hoy. Resultaba lógico entonces que los docentes universitarios superaran los límites del profesionalismo y del academicismo y se lanzaran a ratificar definitivamente su carácter de trabajadores.<br>
		En un espacio de trabajo tan singular, en donde prevalecían los prestigios académicos, las particularidades disciplinarias y una estructura con muchos resabios feudales y corporativistas, siempre había resultado muy dificultoso instalar una organización que no hiciera distingos entre docentes rentados y ad honorem, regulares e interinos, con dedicación exclusiva o simple, investigadores o docentes. Además del hecho concreto democratizador que supone reconocer para cada docente el valor de un voto en las asambleas, muy diferente de la votación calificada y desproporcional de los órganos directivos universitarios. En esos primeros años encontraron a muchos docentes trabajando por la construcción gremial unitaria en aquellos lugares en donde no existía organización sindical y defendiendo siempre el antiburocratismo allí mismo en donde ya se expresaban las tendencias burocráticas y propatronales en los gremios con mayor antigüedad. Quedan como grandes recuerdos de las luchas de los docentes universitarios de la UBA, las multitudinarias asambleas del CBC del 85, 86 y 87 que desembocaron en la Gremial con más votación de la UBA, las grandes huelgas del 88 (que acompañaron las de todo el sistema educativo), los dos meses de huelga de comienzos del 89.
		En lo que respecta a la UBA, siempre resultó un desafío hacerse cargo por aquellos años de las comisiones gremiales de varias Facultades al mismo tiempo que se conformaba la CIDUBA (Coordinadora Interfacultades Docente de la UBA), cuya dirección transitoria fue el primer y lamentable intento de vincular estrechamente los objetivos gremiales con los destinos de la hegemonía universitaria o política (el radicalismo, por aquellos tiempos también el llamado peronismo renovador).<br>
		Surgió así la posibilidad de conformar la Aduba original, que se fue desplazando rápidamente no solo a prácticas burocráticas y propatronales sino directamente a una política de vaciamiento gremial que le hizo mucho daño a la movilización sindical de los docentes universitarios de la UBA, precisamente en una universidad clave para el combate contra los ajustes presupuestarios. Utilizando el fondo sindical de los descuentos por planilla para desarrollar esta política terminó siendo el brazo gremial primero del shuberofismo para realizar los trabajos sucios de confusionismo y macartismo sindical en el seno de la UBA.<br>
		Después de combates jurídicos y laborales por recuperar el gremio para los docentes universitarios y ante la complicidad del Rectorado y Ministerio de Trabajo en la protección de una cúpula sindical corrupta y nada representativa, activistas docentes de la UBA decidieron poner en pie una nueva alternativa gremial, la AGD (Asociación Gremial Docente de la UBA) poniendo todas sus energías y militantes gremiales para el crecimiento de esta opción que hoy es la única organización verdaderamente gremial de los docentes de la UBA. <br>
		Para la AGD es un orgullo ser un protagonista principal de este proceso que ha desembocado en el reconocimiento jurídico de la organización, aunque lo que más interesa es que sean los propios docentes universitarios de base los que la reconocen como la defensora de sus derechos.<br>
		Fue toda esta experiencia de lucha antiburocrática la que preparó a la AGD para protagonizar en la medida de su fuerzas los acontecimientos de diciembre de 2001 que dieron por tierra con el dúo el De La Rúa-Cavallo y lo que permite actualmente articularse con las luchas populares de trabajadores sindicalizados, piqueteros y estudiantes. La que también preparó la huelga general del 2005, donde tras el plan de lucha del primer cuatrimestre, nos lanzamos a un paro de más de un mes que sacudió la UBA. Fue cuando conquistamos el blanqueo salarial –siendo los únicos trabajadores docentes que logramos hacerlo-, el salario para 2200 puestos de trabajo docentes ad honorem en todo el país, el puntapié para lo que iba a ser otra conquista nacional en 2009: la ley jubilatoria para los docentes universitarios. 
		El relato de las tantas experiencias que protagonizamos los docentes nucleados en nuestra Federación, la CONADU Histórica, y en la AGD de la UBA están en las memorias (que no solo publicamos sino que previamente debatimos de manera colectiva y aprobamos en asamblea). Pero en ese recorrido no podemos dejar de mencionar: las grandes batallas desde 2007 para que se concretara el plan de otorgamiento de salario para los ad honorem, las de 2011 contra los intentos de cesantías masivas por parte del Rectorado, las casi permanentes confrontaciones con el CBC para impedir despidos como fue la lucha de 2014 y 2015, entre tantas otras. Y, sobre todo, las cotidianas y menos visibles intervenciones del gremio junto con los docentes en cada facultad, en cada lugar de trabajo, laboratorio o aula.
		Desde aquella asamblea fundacional con los “pioneros” 150 compañeras y compañeros hasta la realidad de hoy de más de 4500 afiliados, desde aquellas pocas comisiones internas por facultad a estas once facultades y tres colegios preuniversitarios organizados en AGD, ha pasado una larga historia, nuestro presente, el de los docentes de la UBA. Del que podemos estar orgullosos.
		es, con las comisiones internas de algunas facultades, y hoy es una organización gremial que cuenta con más de 4500 afiliados.  </p>
		<hr>
		</section>
	</div>	
</div>

<?php get_footer(); ?>